version: '3.9'
services:
#  server:
#    build:
#      context: .
#      dockerfile: docker/Dockerfile
#      target: develop
#    container_name: go-server
#    ports:
#      - "8080:8080"
#      - "40000:40000"
#    volumes:
#      - .:app
#    depends_on:
#      - db
#    security_opt:
#      - apparmor:unconfined
#    cap_add:
#      - SYS_PTRACE

  #db
  db:
    build:
      context: $PWD/db
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - $PWD/db/init:/docker-entrypoint-initdb.d
      - $PWD/db/sql:/docker-entrypoint-initdb.d