version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: develop
    container_name: web-go
    ports:
      - "8080:8080"
      - "40000:40000"
    volumes:
      - .:/app
    depends_on:
      - db
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    networks:
      - migrate-ntwk

  #db
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: web-postgres
    expose:
      - 5432
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - migrate-ntwk

  migrate:
    tty: true
    build:
      context: .
      dockerfile: ./docker/migrate/Dockerfile
    container_name: go-migrate
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    working_dir: /docker-entrypoint-initdb.d
    depends_on:
      - db
    networks:
      - migrate-ntwk

networks:
  migrate-ntwk:

